server.port=8089
spring.application.name=ai-service

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Oracle Database Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=system
spring.datasource.password=admin
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.config.import=optional:configserver:

# Resilience4j Circuit Breaker Config
resilience4j.circuitbreaker.instances.weatherService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.weatherService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.weatherService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.weatherService.slidingWindowType=TIME_BASED
resilience4j.circuitbreaker.instances.weatherService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.weatherService.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.weatherService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.weatherService.eventConsumerBufferSize=10

# Resilience4j TimeLimiter Config (3s timeout)
resilience4j.timelimiter.instances.weatherService.timeoutDuration=3s
resilience4j.timelimiter.instances.weatherService.cancelRunningFuture=true
