import { useState, useEffect } from 'react';
import { Card, AIPanel } from '../../components/common/UIComponents';
import { Send, AlertTriangle, CloudRain, Droplets, MapPin, CheckCircle, FilePlus, Brain, Loader } from 'lucide-react';
import Swal from 'sweetalert2';

const DISTRICTS = ['Coimbatore', 'Chennai', 'Madurai', 'Salem', 'Tiruchirappalli', 'Tirunelveli', 'Erode', 'Cuddalore', 'Nagapattinam'];

export default function DisasterPrediction() {
  const [district, setDistrict] = useState('Coimbatore');
  const [warningType, setWarningType] = useState('Heavy Rain');
  const [message, setMessage] = useState('');
  
  const [aiData, setAiData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchPrediction = async () => {
      try {
        const response = await fetch('http://localhost:8081/api/v1/ai/weather-advisory');
        const data = await response.json();
        setAiData(data.data);
      } catch (err) {
        setAiData({
          summary: "Error connecting to AI service. Using cached prediction.",
          recommendation: "Ensure backup communications are active.",
          confidence: 50,
          targetDistrict: "Chennai",
          warningType: "Heavy Rain",
          advisoryMessage: "Please stand by for further instructions."
        });
      } finally {
        setLoading(false);
      }
    };
    fetchPrediction();
  }, []);

  const handleIssueAdvisory = (e) => {
    e.preventDefault();
    Swal.fire({
      title: 'Advisory Sent!',
      text: `Warning dispatched to the Collector of ${district}.`,
      icon: 'success',
      confirmButtonText: 'OK',
      timer: 3000
    });
  };

  const handleDraftAdvisory = () => {
    if (aiData) {
      setDistrict(aiData.targetDistrict || 'Chennai');
      setWarningType(aiData.warningType || 'Heavy Rain');
      setMessage(aiData.advisoryMessage || 'Warning generated by AI.');
    }
    
    // Smooth scroll to the form if needed
    window.scrollTo({ top: document.body.scrollHeight, behavior: 'smooth' });
    
    Swal.fire({
      title: 'Draft Created',
      text: 'The advisory form has been automatically populated based on AI recommendations.',
      icon: 'info',
      timer: 2000,
      showConfirmButton: false
    });
  };

  return (
    <div>
      <div className="page-header">
        <div>
          <div className="page-title"><Brain size={24} style={{ display: 'inline', marginRight: '8px', verticalAlign: 'text-bottom' }} /> AI Disaster Prediction</div>
          <div className="page-subtitle">Predictive models for weather, floods, and large-scale threats</div>
        </div>
      </div>
      
      <div className="grid-2">
        {loading ? (
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', background: 'white', borderRadius: 'var(--radius-lg)', border: '1px solid var(--border)', padding: '40px' }}>
            <Loader className="spinner" size={32} color="var(--primary)" style={{ marginBottom: 16 }} />
            <h3 style={{ color: 'var(--text)', marginBottom: 8 }}>AI analyzing live weather APIs...</h3>
            <p style={{ color: 'var(--text-muted)' }}>Generating localized risk prediction for Tamil Nadu.</p>
          </div>
        ) : (
          <AIPanel 
            title="Real-Time AI Weather & Risk Model"
            summary={aiData?.summary || "No summary available."}
            recommendation={aiData?.recommendation || "No recommendation."}
            confidence={aiData?.confidence || 70}
            action={
              <button className="btn btn-secondary" onClick={handleDraftAdvisory} style={{ marginTop: '8px' }}>
                <FilePlus size={14} /> Draft Advisory from Prediction
              </button>
            }
          />
        )}
        
        <Card title="Issue Official Collector Advisory" icon={<AlertTriangle size={18} color="var(--severity-high)" />}>
          <form onSubmit={handleIssueAdvisory}>
            <div className="form-group" style={{ marginBottom: '12px' }}>
              <label className="form-label" style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                <MapPin size={14} /> Target District
              </label>
              <select 
                className="form-select" 
                value={district} 
                onChange={e => setDistrict(e.target.value)}
              >
                {DISTRICTS.map(d => <option key={d}>{d}</option>)}
              </select>
            </div>
            
            <div className="form-group" style={{ marginBottom: '12px' }}>
              <label className="form-label">Warning Type</label>
              <select 
                className="form-select" 
                value={warningType}
                onChange={e => setWarningType(e.target.value)}
              >
                <option value="Heavy Rain">Heavy Rain / Red Alert</option>
                <option value="Dam Opening">Dam Opening / Flood Warning</option>
                <option value="Cyclone">Cyclone / Gale Wind Warning</option>
                <option value="Tsunami">Tsunami Alert</option>
              </select>
            </div>
            
            <div className="form-group" style={{ marginBottom: '16px' }}>
              <label className="form-label">Advisory Message</label>
              <textarea 
                className="form-textarea" 
                rows={3} 
                value={message}
                onChange={e => setMessage(e.target.value)}
              />
            </div>
            
            <button type="submit" className="btn btn-danger" style={{ width: '100%', justifyContent: 'center' }}>
              <Send size={16} /> Dispatch Warning to Collector
            </button>
          </form>
        </Card>
      </div>
    </div>
  );
}
