server.port=8084
spring.application.name=incident-service

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# MongoDB Local Configuration
spring.data.mongodb.uri=mongodb://mongo:27017/alertgov_media

# Increase upload size for images/videos
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.config.import=optional:configserver:
